name: Initiate Release
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: |
          Version to release, e.g. 1.1.0; 
          Only main and develop branch are allowed to release, release from main branch will create hotfix. 
        required: true
      release_summary:
        type: string
        description: Release summary will be put into the PR description and release notes
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  release_workflow:
    # only run on main and develop branch for workflow_dispatch event
    if: ${{ github.event_name != 'workflow_dispatch' || ( github.ref_name == 'main' || github.ref_name == 'develop')}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      deployments: write
    steps:
      - name: Gitflow release workflow
        id: gitflow-release
        uses: kzhou57/gitflow-workflow-action@develop
        with:
          develop_branch: "develop"
          main_branch: "main"
          merge_back_from_main: false
          version: ${{ inputs.version }}
          release_summary: ${{ inputs.release_summary }}
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # WORKAROUND: to trigger the CI workflow on the release branch (the PR and branch created by default GITHUB_TOKEN does not trigger the CI workflow)
      #   See the discussion here: https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs
      - name: Close & Reopen release PR
        # only run when the release PR is created
        if: ${{ steps.gitflow-release.outputs.type == 'release' || steps.gitflow-release.outputs.type == 'hotfix'}}
        shell: bash
        run: |
          # Close the PR
          gh pr close -R "${{ github.repository }}" \
            --comment "Temporarily close release PR" \
            ${{ steps.gitflow-release.outputs.pull_number }}
          # Reopen the PR
          gh pr reopen -R "${{ github.repository }}" \
            --comment "Reopen release PR to trigger the workflows" \
            ${{ steps.gitflow-release.outputs.pull_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
