name: Release Workflow
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: |
          Version to release, e.g. 1.1.0
          Note : Only main and develop branch are allowed to release, release from main branch will create hotfix
        required: true
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  release_workflow:
    # only run on main and develop branch for workflow_dispatch event
    if: ${{ github.event_name != 'workflow_dispatch' || ( github.ref_name == 'main' || github.ref_name == 'develop')}}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      deployments: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: gitflow-workflow-action release workflows
        uses: kzhou57/gitflow-workflow-action@develop
        with:
          develop_branch: "develop"
          main_branch: "main"
          merge_back_from_main: false
          version: ${{ inputs.version }}
          release_summary: |
            Production release: 
              - This PR should trigger a production release automatically
              - Once the release is done, please close this PR, a release tag will be created and the code will be merged back to develop branch automatically
          dry_run: false

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}